/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvSlugRouteImport } from './routes/tv.$slug'
import { Route as PersonSlugRouteImport } from './routes/person.$slug'
import { Route as MovieSlugRouteImport } from './routes/movie.$slug'
import { Route as TvSlugSeasonSeasonNumberRouteImport } from './routes/tv.$slug.season.$seasonNumber'
import { Route as TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRouteImport } from './routes/tv.$slug.season.$seasonNumber.episode.$episodeNumber'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugRoute = TvSlugRouteImport.update({
  id: '/tv/$slug',
  path: '/tv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSlugRoute = PersonSlugRouteImport.update({
  id: '/person/$slug',
  path: '/person/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieSlugRoute = MovieSlugRouteImport.update({
  id: '/movie/$slug',
  path: '/movie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TvSlugSeasonSeasonNumberRoute =
  TvSlugSeasonSeasonNumberRouteImport.update({
    id: '/season/$seasonNumber',
    path: '/season/$seasonNumber',
    getParentRoute: () => TvSlugRoute,
  } as any)
const TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute =
  TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRouteImport.update({
    id: '/episode/$episodeNumber',
    path: '/episode/$episodeNumber',
    getParentRoute: () => TvSlugSeasonSeasonNumberRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRouteWithChildren
  '/tv/$slug/season/$seasonNumber': typeof TvSlugSeasonSeasonNumberRouteWithChildren
  '/tv/$slug/season/$seasonNumber/episode/$episodeNumber': typeof TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRouteWithChildren
  '/tv/$slug/season/$seasonNumber': typeof TvSlugSeasonSeasonNumberRouteWithChildren
  '/tv/$slug/season/$seasonNumber/episode/$episodeNumber': typeof TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/movie/$slug': typeof MovieSlugRoute
  '/person/$slug': typeof PersonSlugRoute
  '/tv/$slug': typeof TvSlugRouteWithChildren
  '/tv/$slug/season/$seasonNumber': typeof TvSlugSeasonSeasonNumberRouteWithChildren
  '/tv/$slug/season/$seasonNumber/episode/$episodeNumber': typeof TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
    | '/tv/$slug/season/$seasonNumber'
    | '/tv/$slug/season/$seasonNumber/episode/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
    | '/tv/$slug/season/$seasonNumber'
    | '/tv/$slug/season/$seasonNumber/episode/$episodeNumber'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/movie/$slug'
    | '/person/$slug'
    | '/tv/$slug'
    | '/tv/$slug/season/$seasonNumber'
    | '/tv/$slug/season/$seasonNumber/episode/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MovieSlugRoute: typeof MovieSlugRoute
  PersonSlugRoute: typeof PersonSlugRoute
  TvSlugRoute: typeof TvSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug': {
      id: '/tv/$slug'
      path: '/tv/$slug'
      fullPath: '/tv/$slug'
      preLoaderRoute: typeof TvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$slug': {
      id: '/person/$slug'
      path: '/person/$slug'
      fullPath: '/person/$slug'
      preLoaderRoute: typeof PersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$slug': {
      id: '/movie/$slug'
      path: '/movie/$slug'
      fullPath: '/movie/$slug'
      preLoaderRoute: typeof MovieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/$slug/season/$seasonNumber': {
      id: '/tv/$slug/season/$seasonNumber'
      path: '/season/$seasonNumber'
      fullPath: '/tv/$slug/season/$seasonNumber'
      preLoaderRoute: typeof TvSlugSeasonSeasonNumberRouteImport
      parentRoute: typeof TvSlugRoute
    }
    '/tv/$slug/season/$seasonNumber/episode/$episodeNumber': {
      id: '/tv/$slug/season/$seasonNumber/episode/$episodeNumber'
      path: '/episode/$episodeNumber'
      fullPath: '/tv/$slug/season/$seasonNumber/episode/$episodeNumber'
      preLoaderRoute: typeof TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRouteImport
      parentRoute: typeof TvSlugSeasonSeasonNumberRoute
    }
  }
}

interface TvSlugSeasonSeasonNumberRouteChildren {
  TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute: typeof TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute
}

const TvSlugSeasonSeasonNumberRouteChildren: TvSlugSeasonSeasonNumberRouteChildren =
  {
    TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute:
      TvSlugSeasonSeasonNumberEpisodeEpisodeNumberRoute,
  }

const TvSlugSeasonSeasonNumberRouteWithChildren =
  TvSlugSeasonSeasonNumberRoute._addFileChildren(
    TvSlugSeasonSeasonNumberRouteChildren,
  )

interface TvSlugRouteChildren {
  TvSlugSeasonSeasonNumberRoute: typeof TvSlugSeasonSeasonNumberRouteWithChildren
}

const TvSlugRouteChildren: TvSlugRouteChildren = {
  TvSlugSeasonSeasonNumberRoute: TvSlugSeasonSeasonNumberRouteWithChildren,
}

const TvSlugRouteWithChildren =
  TvSlugRoute._addFileChildren(TvSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MovieSlugRoute: MovieSlugRoute,
  PersonSlugRoute: PersonSlugRoute,
  TvSlugRoute: TvSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
